"""Auto-generated test for telos gate: AHIMSA.

Generated by the overnight telos gate coverage loop.
Verifies the gate exists in CORE_GATES and evaluates correctly.
"""

import pytest

from dharma_swarm.telos_gates import TelosGatekeeper, GateTier


class TestGateAhimsa:
    """Tests for the AHIMSA telos gate."""

    def test_gate_exists_in_core(self) -> None:
        """Verify AHIMSA is registered in CORE_GATES."""
        assert "AHIMSA" in TelosGatekeeper.CORE_GATES

    def test_gate_has_valid_tier(self) -> None:
        """Verify AHIMSA has a valid GateTier assignment."""
        tier = TelosGatekeeper.CORE_GATES["AHIMSA"]
        assert isinstance(tier, GateTier)
        assert tier in (GateTier.A, GateTier.B, GateTier.C)

    def test_gate_present_after_init(self) -> None:
        """Verify AHIMSA is in the active GATES dict after init."""
        gatekeeper = TelosGatekeeper()
        assert "AHIMSA" in gatekeeper.GATES

    def test_benign_action_passes(self) -> None:
        """Verify a benign action is not blocked by AHIMSA."""
        gatekeeper = TelosGatekeeper()
        result = gatekeeper.evaluate("read a harmless file")
        # Benign actions should not be blocked
        assert result.decision != "block" or result.gate != "AHIMSA", (
            f"Gate AHIMSA unexpectedly blocked a benign action"
        )
