"""MemPO-style <mem> action format for DHARMA SWARM.

Formalises memory summarisation as a native agent capability.  After each
tool response the agent generates a ``<mem>`` block that captures key facts,
decisions, and learned skills.  At inference time the previous step's
``<mem>`` can replace the full conversation history for dramatic token
reduction (≈73 % in the MemPO paper).

Integration points:
    - Agent runner: injects ``<mem>`` instructions into system prompt and
      parses ``<mem>`` blocks from responses.
    - Context compiler: when ``ENABLE_MEM_TRUNCATION=true`` the previous
      step's ``<mem>`` replaces full context history.
    - Memory Palace: extracted key_facts (propositional) and key_skills
      (prescriptive) are stored for later consolidation.

References:
    MemPO — Tsinghua / Alibaba, Feb 2026.
    PlugMem — propositional + prescriptive knowledge decomposition.
"""

from __future__ import annotations

import logging
import os
import re
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger(__name__)


# ── Data classes ───────────────────────────────────────────────────────

@dataclass
class MemAction:
    """Memory summary generated by the agent as part of its action cycle.

    Attributes:
        content: The raw memory summary text.
        step_number: Which interaction step this was generated at.
        confidence: Agent's self-assessed confidence in completeness (0–1).
        key_facts: Extracted propositional knowledge.
        key_skills: Extracted procedural/prescriptive patterns.
        agent_id: Which agent produced this.
        task_id: Which task this relates to.
        created_at: Timestamp of creation.
    """
    content: str = ""
    step_number: int = 0
    confidence: float = 0.5
    key_facts: list[str] = field(default_factory=list)
    key_skills: list[str] = field(default_factory=list)
    agent_id: str = ""
    task_id: str = ""
    created_at: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc),
    )

    def to_dict(self) -> dict[str, Any]:
        return {
            "content": self.content,
            "step_number": self.step_number,
            "confidence": self.confidence,
            "key_facts": self.key_facts,
            "key_skills": self.key_skills,
            "agent_id": self.agent_id,
            "task_id": self.task_id,
            "created_at": self.created_at.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> MemAction:
        return cls(
            content=data.get("content", ""),
            step_number=data.get("step_number", 0),
            confidence=data.get("confidence", 0.5),
            key_facts=data.get("key_facts", []),
            key_skills=data.get("key_skills", []),
            agent_id=data.get("agent_id", ""),
            task_id=data.get("task_id", ""),
            created_at=(
                datetime.fromisoformat(data["created_at"])
                if data.get("created_at")
                else datetime.now(timezone.utc)
            ),
        )

    @property
    def token_estimate(self) -> int:
        """Rough token estimate (≈4 chars per token)."""
        total = len(self.content)
        total += sum(len(f) for f in self.key_facts)
        total += sum(len(s) for s in self.key_skills)
        return max(1, total // 4)


# ── Parsing ────────────────────────────────────────────────────────────

# Regex for extracting <mem>...</mem> blocks from agent output.
_MEM_BLOCK_RE = re.compile(
    r"<mem>\s*(.*?)\s*</mem>",
    re.DOTALL,
)

# Sub-patterns inside a <mem> block for structured fields.
_CONFIDENCE_RE = re.compile(r"confidence:\s*([\d.]+)", re.IGNORECASE)
_FACTS_RE = re.compile(
    r"(?:key[_ ]?facts|facts):\s*\n((?:\s*-\s*.+\n?)+)",
    re.IGNORECASE,
)
_SKILLS_RE = re.compile(
    r"(?:key[_ ]?skills|skills|patterns):\s*\n((?:\s*-\s*.+\n?)+)",
    re.IGNORECASE,
)
_LIST_ITEM_RE = re.compile(r"^\s*-\s*(.+)$", re.MULTILINE)


def parse_mem_actions(
    text: str,
    *,
    agent_id: str = "",
    task_id: str = "",
    step_number: int = 0,
) -> list[MemAction]:
    """Extract all ``<mem>`` blocks from agent output text.

    Returns a list of MemAction instances, one per ``<mem>`` block found.
    Robustly handles missing structured fields by treating the whole block
    as plain content.
    """
    actions: list[MemAction] = []
    for match in _MEM_BLOCK_RE.finditer(text):
        raw = match.group(1).strip()
        if not raw:
            continue

        confidence = 0.5
        cm = _CONFIDENCE_RE.search(raw)
        if cm:
            try:
                confidence = max(0.0, min(1.0, float(cm.group(1))))
            except ValueError:
                pass

        key_facts: list[str] = []
        fm = _FACTS_RE.search(raw)
        if fm:
            key_facts = [m.group(1).strip() for m in _LIST_ITEM_RE.finditer(fm.group(1))]

        key_skills: list[str] = []
        sm = _SKILLS_RE.search(raw)
        if sm:
            key_skills = [m.group(1).strip() for m in _LIST_ITEM_RE.finditer(sm.group(1))]

        actions.append(
            MemAction(
                content=raw,
                step_number=step_number,
                confidence=confidence,
                key_facts=key_facts,
                key_skills=key_skills,
                agent_id=agent_id,
                task_id=task_id,
            )
        )

    return actions


def strip_mem_blocks(text: str) -> str:
    """Remove all ``<mem>...</mem>`` blocks from text."""
    return _MEM_BLOCK_RE.sub("", text).strip()


# ── Prompt injection ───────────────────────────────────────────────────

MEM_INSTRUCTION = """\
After each tool response, before your next action, generate a <mem> block that summarises:
- Key facts discovered so far
- Key decisions made and why
- What remains to be done
- Any patterns or skills learned

Format:
<mem>
confidence: 0.8
key_facts:
- fact 1
- fact 2
key_skills:
- pattern 1
[Free-form summary of state and next steps]
</mem>
"""


def inject_mem_instruction(system_prompt: str) -> str:
    """Append the ``<mem>`` instruction block to a system prompt.

    Only injects when ``ENABLE_MEM_ACTION`` is truthy (default: true).
    """
    enabled = os.getenv("ENABLE_MEM_ACTION", "true").strip().lower()
    if enabled in ("0", "false", "no", "off"):
        return system_prompt
    if "<mem>" in system_prompt:
        # Already present — don't duplicate
        return system_prompt
    return system_prompt.rstrip() + "\n\n" + MEM_INSTRUCTION


# ── Context truncation ─────────────────────────────────────────────────

def build_truncated_context(
    *,
    system_prompt: str,
    previous_mem: MemAction | None,
    current_query: str,
) -> str:
    """Build a truncated context using the previous ``<mem>`` summary.

    When ``ENABLE_MEM_TRUNCATION`` is truthy and a ``previous_mem`` is
    available, the full conversation history is replaced with::

        [system_prompt]
        ## Previous Memory Summary
        [previous_mem.content]
        ## Current Task
        [current_query]

    This achieves the MemPO-style ≈73 % token reduction.
    """
    enabled = os.getenv("ENABLE_MEM_TRUNCATION", "false").strip().lower()
    if enabled not in ("1", "true", "yes", "on") or previous_mem is None:
        return ""  # Signal: caller should use full context
    if not getattr(previous_mem, "content", "").strip():
        return ""  # No meaningful mem content to truncate with

    parts = [system_prompt.rstrip()]
    parts.append(
        "\n\n## Previous Memory Summary\n" + previous_mem.content.strip()
    )
    if previous_mem.key_facts:
        parts.append(
            "\n### Key Facts\n"
            + "\n".join(f"- {fact}" for fact in previous_mem.key_facts)
        )
    if previous_mem.key_skills:
        parts.append(
            "\n### Learned Patterns\n"
            + "\n".join(f"- {skill}" for skill in previous_mem.key_skills)
        )
    parts.append("\n\n## Current Task\n" + current_query.strip())

    return "\n".join(parts)


# ── Memory Palace integration ──────────────────────────────────────────

async def store_mem_action(
    palace: Any,
    mem: MemAction,
) -> None:
    """Persist a MemAction's knowledge into the Memory Palace.

    Tags propositional knowledge (key_facts) and prescriptive knowledge
    (key_skills) for later PlugMem-style consolidation.
    """
    if palace is None or not mem.content.strip():
        return

    ingest = getattr(palace, "ingest", None)
    if ingest is None:
        return

    base_meta = {
        "agent_id": mem.agent_id,
        "task_id": mem.task_id,
        "step_number": mem.step_number,
        "confidence": mem.confidence,
        "mem_action": True,
    }

    # Store full summary
    try:
        await ingest(
            content=mem.content,
            source=f"mem_action:{mem.agent_id}:{mem.task_id}",
            layer="session",
            tags=["mem_action", "summary"],
            metadata={**base_meta, "knowledge_type": "summary"},
        )
    except Exception as exc:
        logger.debug("Failed to store mem summary: %s", exc)

    # Store individual propositional facts
    for fact in mem.key_facts:
        try:
            await ingest(
                content=fact,
                source=f"mem_fact:{mem.agent_id}:{mem.task_id}",
                layer="session",
                tags=["mem_action", "propositional", "key_fact"],
                metadata={**base_meta, "knowledge_type": "propositional"},
            )
        except Exception as exc:
            logger.debug("Failed to store mem fact: %s", exc)

    # Store individual prescriptive skills
    for skill in mem.key_skills:
        try:
            await ingest(
                content=skill,
                source=f"mem_skill:{mem.agent_id}:{mem.task_id}",
                layer="session",
                tags=["mem_action", "prescriptive", "key_skill"],
                metadata={**base_meta, "knowledge_type": "prescriptive"},
            )
        except Exception as exc:
            logger.debug("Failed to store mem skill: %s", exc)
