#!/usr/bin/env python3
"""Generate seed Ashby citations linking passages to dharma_swarm code.

Run once to populate ~/.dharma/citations/seed_ashby_citations.jsonl
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4

OUTPUT = Path.home() / ".dharma" / "citations" / "seed_ashby_citations.jsonl"


def _id() -> str:
    return uuid4().hex[:16]


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


CITATIONS: list[dict] = [
    # ---- Chapter 11: Law of Requisite Variety ----
    {
        "id": _id(),
        "passage_text": "This is the law of Requisite Variety. To put it more picturesquely: only variety in R can force down the variety due to D; only variety can destroy variety.",
        "source_work": "ashby_1956_introduction_to_cybernetics",
        "source_location": "chapter_11:section_11/7",
        "target_type": "principle",
        "target_id": "dharma_swarm/dharma_kernel.py::MetaPrinciple.REQUISITE_VARIETY",
        "relationship": "grounds",
        "evidence": "The kernel names this as a meta-principle. Ashby's law is the formal theorem behind it. The current formal_constraint (len(available_agents) >= len(distinct_task_types)) confuses headcount with variety -- Ashby's law is about distinguishable responses, not agent count.",
        "verified": False,
        "verification_test": "Path('/Users/dhyana/dharma_swarm/dharma_swarm/dharma_kernel.py').exists()",
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
    {
        "id": _id(),
        "passage_text": "Only variety in R can force down the variety due to D; only variety can destroy variety.",
        "source_work": "ashby_1956_introduction_to_cybernetics",
        "source_location": "chapter_11:section_11/7",
        "target_type": "code_file",
        "target_id": "dharma_swarm/telos_gates.py::GateRegistry",
        "relationship": "grounds",
        "evidence": "GateRegistry implements the Variety Expansion Protocol -- the mechanism by which the gate set can grow to match threat variety. This is a direct attempt to satisfy Ashby's law: as disturbance variety grows, regulator variety must grow to match.",
        "verified": False,
        "verification_test": "Path('/Users/dhyana/dharma_swarm/dharma_swarm/telos_gates.py').exists()",
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
    {
        "id": _id(),
        "passage_text": "R's capacity as a regulator cannot exceed R's capacity as a channel of communication.",
        "source_work": "ashby_1956_introduction_to_cybernetics",
        "source_location": "chapter_11:section_11/12",
        "target_type": "code_file",
        "target_id": "dharma_swarm/telos_gates.py::TelosGatekeeper.evaluate",
        "relationship": "violates",
        "evidence": "The TelosGatekeeper uses keyword matching (~56 tokens, ~5.8 bits capacity) against a natural-language disturbance space of thousands of bits. By Ashby's channel capacity theorem, the gatekeeper can reduce outcome variety by at most 6 bits. The remaining disturbance variety flows through unblocked. This is a structural violation, not a bug to fix with more keywords.",
        "verified": False,
        "verification_test": "Path('/Users/dhyana/dharma_swarm/dharma_swarm/telos_gates.py').exists()",
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
    {
        "id": _id(),
        "passage_text": "It has nothing to do with the properties of matter. So if the law is stated in the form 'No machine can...', it is not to be overthrown by the invention of some new device or some new electronic circuit, or the discovery of some new element.",
        "source_work": "ashby_1956_introduction_to_cybernetics",
        "source_location": "chapter_11:section_11/10",
        "target_type": "code_file",
        "target_id": "dharma_swarm/policy_compiler.py::PolicyCompiler.check_action",
        "relationship": "challenges",
        "evidence": "The PolicyCompiler uses semantic similarity (bag-of-words cosine) to evaluate rule violations. Ashby's epistemological claim means no amount of engineering cleverness within this approach can overcome the fundamental variety gap. The solution requires a fundamentally different architecture (LLM-grade evaluator), not a better similarity metric.",
        "verified": False,
        "verification_test": "Path('/Users/dhyana/dharma_swarm/dharma_swarm/policy_compiler.py').exists()",
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
    {
        "id": _id(),
        "passage_text": "So far as his power of regulation was concerned, the law says that his control amounted to just 1 man-power, and no more.",
        "source_work": "ashby_1956_introduction_to_cybernetics",
        "source_location": "chapter_11:section_11/13",
        "target_type": "code_function",
        "target_id": "dharma_swarm/orchestrator.py::Orchestrator.route_next",
        "relationship": "challenges",
        "evidence": "Ashby's Hitler example: one person's regulatory capacity is bounded by one person's bandwidth. The Orchestrator is a single-threaded async loop. Its variety is bounded by its fixed routing algorithm -- it cannot produce responses it was not programmed to produce. The 5-system concurrent orchestrator helps (5 parallel channels) but each channel is itself a fixed-variety loop.",
        "verified": False,
        "verification_test": "Path('/Users/dhyana/dharma_swarm/dharma_swarm/orchestrator.py').exists()",
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
    {
        "id": _id(),
        "passage_text": "H(E)'s minimum is H(D) - H(R), a deduction similar to that of the previous section. It says simply that the minimal value of E's entropy can be forced down below that of D only by an equal increase in that of R.",
        "source_work": "ashby_1956_introduction_to_cybernetics",
        "source_location": "chapter_11:section_11/8",
        "target_type": "code_file",
        "target_id": "dharma_swarm/stigmergy.py::StigmergyStore",
        "relationship": "challenges",
        "evidence": "Stigmergy is the primary channel carrying disturbance information from D (environment) to R (governance). Ashby's entropy bound means the regulatory capacity is bounded by this channel's capacity. But the TelosGatekeeper does NOT read stigmergy marks -- the channel is severed. Like an insect's optic nerve cut: regulatory capacity drops to zero regardless of R's available moves.",
        "verified": False,
        "verification_test": "Path('/Users/dhyana/dharma_swarm/dharma_swarm/stigmergy.py').exists()",
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
    # ---- Chapter 12: Error-Controlled Regulation ----
    {
        "id": _id(),
        "passage_text": "So the more successful R is in keeping E constant, the more does R block the channel by which it is receiving its necessary information. Clearly, any success by R can at best be partial.",
        "source_work": "ashby_1956_introduction_to_cybernetics",
        "source_location": "chapter_12:section_12/5",
        "target_type": "code_file",
        "target_id": "dharma_swarm/witness.py::WitnessAuditor",
        "relationship": "grounds",
        "evidence": "The WitnessAuditor is an error-controlled regulator: it observes E (system state) rather than D (disturbances) directly. Ashby's impossibility theorem applies -- as the system gets healthier, the audit signal gets lower-variety, degrading the auditor's information channel. The auditor should be CONCERNED when all signals read green, not reassured.",
        "verified": False,
        "verification_test": "Path('/Users/dhyana/dharma_swarm/dharma_swarm/witness.py').exists()",
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
    {
        "id": _id(),
        "passage_text": "Small errors are allowed to occur; then, by giving their information to R, they make possible a regulation against great errors. This is the basic theory, in terms of communication, of the simple feedback regulator.",
        "source_work": "ashby_1956_introduction_to_cybernetics",
        "source_location": "chapter_12:section_12/6",
        "target_type": "code_file",
        "target_id": "dharma_swarm/evolution.py::DarwinEngine.score_fitness",
        "relationship": "grounds",
        "evidence": "The DarwinEngine allows small fitness failures (errors) in agent configurations as the information signal for evolutionary improvement. Configurations that fail non-catastrophically provide the signal that drives mutation and selection. This is Ashby's error-controlled feedback: small errors enable regulation against large ones.",
        "verified": False,
        "verification_test": "Path('/Users/dhyana/dharma_swarm/dharma_swarm/evolution.py').exists()",
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
    {
        "id": _id(),
        "passage_text": "'Trial and error' is about as misleading as it can be. 'Trial' is in the singular, whereas the essence of the method is that the attempts go on and on. 'Error' is also ill-chosen, for the important element is the success at the end. 'Hunt and stick' seems to describe the process both more vividly and more accurately.",
        "source_work": "ashby_1956_introduction_to_cybernetics",
        "source_location": "chapter_12:section_12/11",
        "target_type": "code_file",
        "target_id": "dharma_swarm/evolution.py::DarwinEngine",
        "relationship": "instantiates",
        "evidence": "The DarwinEngine IS Ashby's hunt-and-stick mechanism. It mutates agent configurations (hunt), evaluates fitness, and retains high-fitness configurations (stick). The evolution archive at ~/.dharma/evolution/ is the protocol of the machine's hunt-and-stick trajectory.",
        "verified": False,
        "verification_test": "Path('/Users/dhyana/dharma_swarm/dharma_swarm/evolution.py').exists()",
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
    {
        "id": _id(),
        "passage_text": "The construction of R makes it a vetoer of all states of equilibrium in T save those in eta. The whole is thus regulatory; and as T and R are here Markovian, the whole will seem to be hunting for a 'desirable' state, and will stick to it when found.",
        "source_work": "ashby_1956_introduction_to_cybernetics",
        "source_location": "chapter_12:section_12/14",
        "target_type": "code_file",
        "target_id": "dharma_swarm/evolution.py::DarwinEngine",
        "relationship": "extends",
        "evidence": "DarwinEngine currently selects FOR fitness but does not structurally VETO unfit equilibria. Ashby's vetoer architecture requires continuous background evaluation of ALL active configurations. A configuration that is a stable equilibrium but telos-misaligned could persist if never evaluated. The vetoer construction demands the DarwinEngine become more aggressive about probing stable states.",
        "verified": False,
        "verification_test": "Path('/Users/dhyana/dharma_swarm/dharma_swarm/evolution.py').exists()",
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
    # ---- Chapter 10: Regulation ----
    {
        "id": _id(),
        "passage_text": "The skilled provider, the ## good ## regulator, would keep the essential variables within normal limits so that an observer of them would not be able to tell what disturbances had threatened, and would even have difficulty in deciding whether any disturbance had occurred.",
        "source_work": "ashby_1956_introduction_to_cybernetics",
        "source_location": "chapter_10:section_10/6",
        "target_type": "code_file",
        "target_id": "dharma_swarm/monitor.py::SystemMonitor",
        "relationship": "grounds",
        "evidence": "The SystemMonitor tracks essential variables (agent success rate, provider health, stigmergy density, resource burn rate). A well-regulated system's essential variables should show flat traces despite environmental disturbances -- exactly Ashby's family provider whose household never knows times are hard. The monitor IS the instrument that measures regulatory quality.",
        "verified": False,
        "verification_test": "Path('/Users/dhyana/dharma_swarm/dharma_swarm/monitor.py').exists()",
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
    # ---- Good Regulator Theorem (Conant-Ashby 1970) ----
    {
        "id": _id(),
        "passage_text": "Every good regulator of a system must be a model of that system.",
        "source_work": "conant_ashby_1970_good_regulator_theorem",
        "source_location": "theorem_statement",
        "target_type": "code_function",
        "target_id": "dharma_swarm/orchestrator.py::Orchestrator._select_idle_agent",
        "relationship": "challenges",
        "evidence": "The orchestrator routes tasks to agents but does not model task content, agent capability profiles, expected outcome distributions, or the disturbance landscape. It uses TF-IDF semantic matching (partial model) plus keyword-based complexity/risk estimation (not a model). GRT demands the orchestrator contain a genuine model of the task-agent mapping.",
        "verified": False,
        "verification_test": "Path('/Users/dhyana/dharma_swarm/dharma_swarm/orchestrator.py').exists()",
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
    {
        "id": _id(),
        "passage_text": "The first effect of this theorem is to change the status of model-making from optional to compulsory.",
        "source_work": "conant_ashby_1970_good_regulator_theorem",
        "source_location": "discussion:p97",
        "target_type": "code_file",
        "target_id": "dharma_swarm/intent_router.py::IntentRouter",
        "relationship": "challenges",
        "evidence": "The IntentRouter has TF-IDF (legitimate model of skill descriptions) but complexity and risk assessment is keyword matching (not a model of task complexity). GRT says model-making is compulsory, not optional -- the keyword portions must be replaced with genuine models.",
        "verified": False,
        "verification_test": "Path('/Users/dhyana/dharma_swarm/dharma_swarm/intent_router.py').exists()",
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
    {
        "id": _id(),
        "passage_text": "Error-controlled regulation is in fact a primitive and demonstrably inferior method of regulation. It is inferior because with it the entropy of the outcomes Z cannot be reduced to zero: its success can only be partial.",
        "source_work": "conant_ashby_1970_good_regulator_theorem",
        "source_location": "section_4:p92-93",
        "target_type": "code_file",
        "target_id": "dharma_swarm/witness.py::WitnessAuditor",
        "relationship": "challenges",
        "evidence": "The WitnessAuditor is purely error-controlled (samples traces, checks after the fact). GRT proves this is demonstrably inferior to cause-controlled regulation. The system needs anticipatory regulation that models disturbances BEFORE they manifest in outcomes, not just retrospective auditing.",
        "verified": False,
        "verification_test": "Path('/Users/dhyana/dharma_swarm/dharma_swarm/witness.py').exists()",
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
    # ---- Chapter 13: Regulation of Very Large Systems ----
    {
        "id": _id(),
        "passage_text": "The fact that 'D' is a single letter in no way implies that what it represents must be internally simple or unitary.",
        "source_work": "ashby_1956_introduction_to_cybernetics",
        "source_location": "chapter_11:section_11/17-11/21",
        "target_type": "code_file",
        "target_id": "dharma_swarm/dharma_swarm/swarm.py",
        "relationship": "grounds",
        "evidence": "Ashby's generality argument: D, R, E, T all admit vectorization and internal structure. The swarm facade (1700+ lines) composes multiple subsystems into a single regulatory apparatus. This IS the vector absorption -- the disturbance space is compound (API failures x hallucinations x resource exhaustion x ...) and the regulator must be compound to match.",
        "verified": False,
        "verification_test": None,
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
    {
        "id": _id(),
        "passage_text": "The regulator is made by another regulator. Is this a reductio ad absurdum? I think not.",
        "source_work": "ashby_1956_introduction_to_cybernetics",
        "source_location": "chapter_13:section_13/22",
        "target_type": "code_file",
        "target_id": "dharma_swarm/evolution.py::DarwinEngine",
        "relationship": "instantiates",
        "evidence": "DarwinEngine (R1) modifies agent configurations (R2) that regulate task execution. The spec-forge process (R1) produces system specifications (R2) that regulate development. The Garden Daemon (R1) spawns Claude subprocesses (R2) that produce ecosystem intelligence. Ashby's key insight: R2's capacity is NOT bounded by R1's -- a simple process can produce a regulator whose capacity exceeds the process that created it.",
        "verified": False,
        "verification_test": "Path('/Users/dhyana/dharma_swarm/dharma_swarm/evolution.py').exists()",
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
    {
        "id": _id(),
        "passage_text": "If the regulator is NOT reducible, designing it takes combinatorially longer than the useful lifetime of the system.",
        "source_work": "ashby_1956_introduction_to_cybernetics",
        "source_location": "chapter_13:section_13/21",
        "target_type": "code_file",
        "target_id": "dharma_swarm/dharma_swarm/models.py",
        "relationship": "grounds",
        "evidence": "dharma_swarm's 5-layer architecture (models -> providers -> runner -> orchestrator -> swarm) is reducible by design. Each layer couples to adjacent layers but not all others. Ashby proves this is not just good engineering but the ONLY way a system of 260+ modules could be designed in human-lifetime timescales. Irreducible regulation of that scale is formally impossible.",
        "verified": False,
        "verification_test": "Path('/Users/dhyana/dharma_swarm/dharma_swarm/models.py').exists()",
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
    {
        "id": _id(),
        "passage_text": "The inborn characteristics of living organisms are simply the strategies that have been found satisfactory over centuries of competition, and built into the young animal so as to be ready for use at the first demand.",
        "source_work": "ashby_1956_introduction_to_cybernetics",
        "source_location": "chapter_12:section_12/22",
        "target_type": "code_file",
        "target_id": "dharma_swarm/dharma_kernel.py::KernelGuard",
        "relationship": "instantiates",
        "evidence": "The 25 kernel principles (SHA-256 signed, immutable) are dharma_swarm's 'inborn characteristics' -- strategies found satisfactory through design and testing, built into the system to be ready at first demand. KernelGuard enforces their integrity. The analogy is precise: these are not learned behaviors but constitutional constraints.",
        "verified": False,
        "verification_test": "Path('/Users/dhyana/dharma_swarm/dharma_swarm/dharma_kernel.py').exists()",
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
    {
        "id": _id(),
        "passage_text": "There is that which threatens the survival of the gene-pattern -- the direct transmission by T from D to E. This part must be blocked at all costs. And there is that which, while it may threaten the gene-pattern, can be transformed (or re-coded) through the regulator R and used to block the effect of the remainder (in T). This information is useful, and should (if the regulator can be provided) be made as large as possible.",
        "source_work": "ashby_1956_introduction_to_cybernetics",
        "source_location": "chapter_11:section_11/13",
        "target_type": "code_file",
        "target_id": "dharma_swarm/subconscious.py::SubconsciousStream",
        "relationship": "grounds",
        "evidence": "The SubconsciousStream (and ShaktiLoop) are variety generators -- they take in environmental variety and re-code it as novel associations, new framings, unexpected connections. Ashby says this information channel SHOULD be made as large as possible. The risk: if these subsystems do not feed back into the regulatory layer (telos gates, policy compiler), they are variety that never reaches the regulator.",
        "verified": False,
        "verification_test": "Path('/Users/dhyana/dharma_swarm/dharma_swarm/subconscious.py').exists()",
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
    {
        "id": _id(),
        "passage_text": "Thus, the use of a regulator to achieve homeostasis and the use of a correction channel to suppress noise are homologous.",
        "source_work": "ashby_1956_introduction_to_cybernetics",
        "source_location": "chapter_11:section_11/12",
        "target_type": "code_file",
        "target_id": "dharma_swarm/stigmergy.py::StigmergyStore.decay",
        "relationship": "grounds",
        "evidence": "Stigmergy decay (moving old marks to archive) IS noise suppression in the regulatory channel. High-redundancy marks (21K with no semantic deduplication) are noise. Decay reduces the noise floor so the signal (high-salience, recent, actionable marks) can reach the regulatory layer. Ashby's Shannon-regulation homology applies directly.",
        "verified": False,
        "verification_test": "Path('/Users/dhyana/dharma_swarm/dharma_swarm/stigmergy.py').exists()",
        "created_at": _now(),
        "created_by": "reading_pipeline",
        "access_count": 0,
        "last_accessed": None,
    },
]


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT, "w") as f:
        for c in CITATIONS:
            f.write(json.dumps(c) + "\n")
    print(f"Wrote {len(CITATIONS)} seed citations to {OUTPUT}")


if __name__ == "__main__":
    main()
