/**
 * DHARMA COMMAND — Route Truth Map.
 *
 * Every dashboard route annotated with the actual truth status of its
 * backend data source(s).  Generated by probing the FastAPI backend on
 * 2026-04-04.
 *
 * Statuses:
 *   live        — endpoint exists AND returns real data
 *   partial     — endpoint exists but returns empty/null (needs data seeding)
 *   decorative  — page renders static/hardcoded UI with no backend call
 *   broken      — endpoint returns 404, 500, or "unable to open database file"
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type TruthStatus = "live" | "partial" | "decorative" | "broken";

export interface EndpointTruth {
  /** API path probed. */
  path: string;
  /** HTTP method. */
  method: "GET" | "POST" | "PATCH" | "DELETE";
  /** HTTP status returned during probe. */
  httpStatus: number;
  /** Truth classification. */
  truth: TruthStatus;
  /** Short note on what we observed. */
  note: string;
}

export interface RouteTruth {
  /** Dashboard route path (e.g. "/dashboard/agents"). */
  route: string;
  /** Overall truth for the page — the *worst* endpoint it depends on. */
  truth: TruthStatus;
  /** All endpoints the page depends on. */
  endpoints: EndpointTruth[];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function worstTruth(statuses: TruthStatus[]): TruthStatus {
  if (statuses.includes("broken")) return "broken";
  if (statuses.includes("decorative")) return "decorative";
  if (statuses.includes("partial")) return "partial";
  return "live";
}

// ---------------------------------------------------------------------------
// Canonical endpoint probe results (2026-04-04)
// ---------------------------------------------------------------------------

const E = {
  // ── Canonical live endpoints ──────────────────────────────────────
  health: {
    path: "/api/health",
    method: "GET" as const,
    httpStatus: 200,
    truth: "live" as const,
    note: "Returns real health data (overall_status, agent_health, anomalies, failure_rate).",
  },
  agents: {
    path: "/api/agents",
    method: "GET" as const,
    httpStatus: 200,
    truth: "live" as const,
    note: "Returns 15+ registered agents with status, model, role, heartbeats.",
  },
  commandsTasks: {
    path: "/api/commands/tasks",
    method: "GET" as const,
    httpStatus: 200,
    truth: "live" as const,
    note: "Returns real task list from SQLite task board.",
  },
  commandsDharma: {
    path: "/api/commands/dharma",
    method: "GET" as const,
    httpStatus: 200,
    truth: "live" as const,
    note: "Returns kernel/corpus/compiler/canary/stigmergy integrity status.",
  },
  chatStatus: {
    path: "/api/chat/status",
    method: "GET" as const,
    httpStatus: 200,
    truth: "live" as const,
    note: "Returns chat contract version, profiles, readiness state.",
  },
  ontologyGraph: {
    path: "/api/ontology/graph",
    method: "GET" as const,
    httpStatus: 200,
    truth: "live" as const,
    note: "Returns real ontology nodes and edges from registry.",
  },

  // ── Endpoints that exist but return empty data ────────────────────
  overview: {
    path: "/api/overview",
    method: "GET" as const,
    httpStatus: 200,
    truth: "live" as const,
    note: "Returns agent_count, task_count, uptime, health_status.",
  },
  modules: {
    path: "/api/modules",
    method: "GET" as const,
    httpStatus: 200,
    truth: "live" as const,
    note: "Returns module truth data with status/live/summary per module.",
  },
  healthAnomalies: {
    path: "/api/health/anomalies",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Endpoint works but returns empty array (no anomalies detected).",
  },
  commandsTraces: {
    path: "/api/commands/traces",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Endpoint works but returns empty array (no traces recorded yet).",
  },
  commandsDispatch: {
    path: "/api/commands/dispatch",
    method: "POST" as const,
    httpStatus: 200,
    truth: "live" as const,
    note: "Returns {dispatched: 0}. Fixed: was broken when CWD != repo root (db path issue).",
  },
  commandsTask: {
    path: "/api/commands/task",
    method: "POST" as const,
    httpStatus: 200,
    truth: "live" as const,
    note: "Creates tasks via task board.",
  },
  ontologyTypes: {
    path: "/api/ontology/types",
    method: "GET" as const,
    httpStatus: 200,
    truth: "live" as const,
    note: "Returns ontology type definitions.",
  },
  ontologyObjects: {
    path: "/api/ontology/objects",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Endpoint works, returns empty for most object types.",
  },
  evolutionArchive: {
    path: "/api/evolution/archive",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Endpoint works but returns empty (no evolution runs yet).",
  },
  fitnessTrend: {
    path: "/api/evolution/fitness-trend",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Endpoint works but returns empty array.",
  },
  evolutionLineage: {
    path: "/api/evolution/lineage/{id}",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Endpoint works but returns empty for any entry ID.",
  },
  stigmergyMarks: {
    path: "/api/stigmergy/marks",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Endpoint works but returns empty (no marks deposited yet).",
  },
  stigmergyHeatmap: {
    path: "/api/stigmergy/heatmap",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Endpoint works but returns empty array.",
  },
  stigmergyGraph: {
    path: "/api/stigmergy/graph",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Endpoint works but returns empty nodes/edges.",
  },
  lineageProvenance: {
    path: "/api/lineage/{id}/provenance",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Endpoint works, returns empty chain for any artifact.",
  },
  lineageImpact: {
    path: "/api/lineage/{id}/impact",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Endpoint works, returns zero descendants for any artifact.",
  },
  agentSpawn: {
    path: "/api/agents/spawn",
    method: "POST" as const,
    httpStatus: 200,
    truth: "live" as const,
    note: "Creates and returns a new agent.",
  },
  agentStop: {
    path: "/api/agents/{id}/stop",
    method: "POST" as const,
    httpStatus: 200,
    truth: "live" as const,
    note: "Stops the specified agent.",
  },
  agentDetail: {
    path: "/api/agents/{id}/detail",
    method: "GET" as const,
    httpStatus: 200,
    truth: "live" as const,
    note: "Returns full agent detail with config, traces, fitness, cost, core files.",
  },
  chatPost: {
    path: "/api/chat",
    method: "POST" as const,
    httpStatus: 200,
    truth: "live" as const,
    note: "SSE streaming chat endpoint (requires provider API keys to produce output).",
  },

  // ── Telemetry endpoints (all exist, all return empty data) ────────
  telemetryOverview: {
    path: "/api/telemetry/overview",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Works but all counters at zero.",
  },
  telemetryRouting: {
    path: "/api/telemetry/routing",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Works but returns zero decisions.",
  },
  telemetryEconomics: {
    path: "/api/telemetry/economics",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Works but all financial values at zero.",
  },
  telemetryAgents: {
    path: "/api/telemetry/agents",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Works but returns empty array.",
  },
  telemetryRoutes: {
    path: "/api/telemetry/routes",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Works but returns empty array.",
  },
  telemetryPolicies: {
    path: "/api/telemetry/policies",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Works but returns empty array.",
  },
  telemetryInterventions: {
    path: "/api/telemetry/interventions",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Works but returns empty array.",
  },
  telemetryEconomicEvents: {
    path: "/api/telemetry/events/economic",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Works but returns empty array.",
  },
  telemetryOutcomes: {
    path: "/api/telemetry/outcomes",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Works but returns empty array.",
  },

  // ── Dashboard-specific endpoints (dgc audit, eval) ────────────────
  auditLatest: {
    path: "/api/audit/latest",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Works but returns null (run 'dgc audit' first).",
  },
  auditTrend: {
    path: "/api/audit/trend",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Works but returns empty array.",
  },
  evalLatest: {
    path: "/api/eval/latest",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Works but returns null (run 'dgc eval run' first).",
  },
  evalTrend: {
    path: "/api/eval/trend",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Works but returns empty array.",
  },
  conversationLogRecent: {
    path: "/api/conversation-log/recent",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Works but returns empty array.",
  },
  conversationLogPromises: {
    path: "/api/conversation-log/promises",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Works but returns empty array.",
  },
  conversationLogStats: {
    path: "/api/conversation-log/stats",
    method: "GET" as const,
    httpStatus: 200,
    truth: "partial" as const,
    note: "Works but all counters at zero.",
  },

  // ── Observatory (misrouted — /api/agents/observatory falls through
  //    to the agent-by-id handler and returns "Agent not found") ──────
  agentsObservatory: {
    path: "/api/agents/observatory",
    method: "GET" as const,
    httpStatus: 200,
    truth: "broken" as const,
    note: "No dedicated observatory endpoint; /api/agents/{id} catches 'observatory' as an agent id and fails.",
  },

  // ── Endpoints that do NOT exist (404) ─────────────────────────────
  fleetConfig: {
    path: "/api/fleet/config",
    method: "GET" as const,
    httpStatus: 404,
    truth: "broken" as const,
    note: "No fleet config router registered.",
  },
  fleetRespawn: {
    path: "/api/fleet/respawn",
    method: "POST" as const,
    httpStatus: 404,
    truth: "broken" as const,
    note: "No fleet respawn router registered.",
  },
  poolTop10Status: {
    path: "/api/pool/top10/status",
    method: "GET" as const,
    httpStatus: 404,
    truth: "broken" as const,
    note: "No pool/top10 router registered.",
  },
  poolTop10Verify: {
    path: "/api/pool/top10/verify",
    method: "POST" as const,
    httpStatus: 404,
    truth: "broken" as const,
    note: "No pool/top10 router registered.",
  },
  poolModelProfile: {
    path: "/api/pool/models/{id}/profile",
    method: "PATCH" as const,
    httpStatus: 404,
    truth: "broken" as const,
    note: "No pool/models router registered.",
  },
  agentConfig: {
    path: "/api/agents/{id}/config",
    method: "PATCH" as const,
    httpStatus: 404,
    truth: "broken" as const,
    note: "No PATCH config endpoint registered on agent router.",
  },
  agentDispatch: {
    path: "/api/agents/{id}/dispatch",
    method: "POST" as const,
    httpStatus: 404,
    truth: "broken" as const,
    note: "No per-agent dispatch endpoint registered.",
  },
  vizTimeline: {
    path: "/api/viz/timeline",
    method: "GET" as const,
    httpStatus: 404,
    truth: "broken" as const,
    note: "Viz router exists but is not registered in api/main.py.",
  },
};

// ---------------------------------------------------------------------------
// Route truth table
// ---------------------------------------------------------------------------

export const ROUTE_TRUTH: RouteTruth[] = [
  // ── Overview (main dashboard page) ────────────────────────────────
  {
    route: "/dashboard",
    truth: "live",
    endpoints: [E.overview, E.health, E.agents, E.commandsTasks, E.chatStatus],
  },

  // ── Agents ────────────────────────────────────────────────────────
  {
    route: "/dashboard/agents",
    truth: "live",
    endpoints: [E.agents, E.agentSpawn, E.agentStop],
  },
  {
    route: "/dashboard/agents/[id]",
    truth: worstTruth(["live", "broken", "broken"]),
    endpoints: [E.agentDetail, E.agentConfig, E.fleetRespawn],
  },

  // ── Tasks ─────────────────────────────────────────────────────────
  {
    route: "/dashboard/tasks",
    truth: "live",
    endpoints: [E.commandsTasks, E.commandsTask],
  },

  // ── Gates (Dharma) ────────────────────────────────────────────────
  {
    route: "/dashboard/gates",
    truth: "live",
    endpoints: [E.commandsDharma],
  },

  // ── Claude chat lane ──────────────────────────────────────────────
  {
    route: "/dashboard/claude",
    truth: "live",
    endpoints: [E.chatStatus, E.chatPost],
  },

  // ── Qwen35 chat lane ─────────────────────────────────────────────
  {
    route: "/dashboard/qwen35",
    truth: "live",
    endpoints: [E.chatStatus, E.chatPost, E.agentDispatch],
  },

  // ── GLM5 chat lane ───────────────────────────────────────────────
  {
    route: "/dashboard/glm5",
    truth: "live",
    endpoints: [E.chatStatus, E.chatPost, E.agentDispatch],
  },

  // ── Runtime ───────────────────────────────────────────────────────
  {
    route: "/dashboard/runtime",
    truth: "live",
    endpoints: [E.chatStatus, E.health],
  },

  // ── Ontology ──────────────────────────────────────────────────────
  {
    route: "/dashboard/ontology",
    truth: "live",
    endpoints: [E.ontologyGraph, E.ontologyTypes],
  },

  // ── Stigmergy ─────────────────────────────────────────────────────
  {
    route: "/dashboard/stigmergy",
    truth: "partial",
    endpoints: [E.stigmergyMarks, E.stigmergyHeatmap],
  },

  // ── Evolution ─────────────────────────────────────────────────────
  {
    route: "/dashboard/evolution",
    truth: "partial",
    endpoints: [E.evolutionArchive, E.fitnessTrend, E.evolutionLineage],
  },

  // ── Lineage ───────────────────────────────────────────────────────
  {
    route: "/dashboard/lineage",
    truth: "partial",
    endpoints: [E.lineageProvenance, E.lineageImpact],
  },

  // ── Observatory ───────────────────────────────────────────────────
  {
    route: "/dashboard/observatory",
    truth: "broken",
    endpoints: [E.agentsObservatory],
  },

  // ── Ecosystem ─────────────────────────────────────────────────────
  {
    route: "/dashboard/ecosystem",
    truth: worstTruth(["partial", "partial", "partial", "live", "broken"]),
    endpoints: [
      E.stigmergyGraph,
      E.stigmergyMarks,
      E.commandsTraces,
      E.agents,
      E.fleetConfig,
    ],
  },

  // ── Synthesizer ───────────────────────────────────────────────────
  {
    route: "/dashboard/synthesizer",
    truth: "partial",
    endpoints: [
      E.ontologyObjects,
      E.stigmergyMarks,
      E.ontologyGraph,
    ],
  },

  // ── Models ────────────────────────────────────────────────────────
  {
    route: "/dashboard/models",
    truth: "broken",
    endpoints: [E.poolTop10Status, E.poolTop10Verify, E.poolModelProfile],
  },

  // ── Telemetry ─────────────────────────────────────────────────────
  {
    route: "/dashboard/telemetry",
    truth: "partial",
    endpoints: [
      E.telemetryOverview,
      E.telemetryRouting,
      E.telemetryEconomics,
      E.telemetryAgents,
      E.telemetryRoutes,
      E.telemetryPolicies,
      E.telemetryInterventions,
      E.telemetryEconomicEvents,
      E.telemetryOutcomes,
    ],
  },

  // ── Qwen35 telemetry ─────────────────────────────────────────────
  {
    route: "/dashboard/qwen35/telemetry",
    truth: "partial",
    endpoints: [E.telemetryOverview],
  },

  // ── Audit ─────────────────────────────────────────────────────────
  {
    route: "/dashboard/audit",
    truth: "partial",
    endpoints: [E.auditLatest, E.auditTrend],
  },

  // ── Eval ──────────────────────────────────────────────────────────
  {
    route: "/dashboard/eval",
    truth: "partial",
    endpoints: [E.evalLatest, E.evalTrend],
  },

  // ── Conversation Log ──────────────────────────────────────────────
  {
    route: "/dashboard/log",
    truth: "partial",
    endpoints: [
      E.conversationLogRecent,
      E.conversationLogPromises,
      E.conversationLogStats,
    ],
  },

  // ── Modules ───────────────────────────────────────────────────────
  {
    route: "/dashboard/modules",
    truth: "live",
    endpoints: [E.modules],
  },

  // ── Timeline ──────────────────────────────────────────────────────
  {
    route: "/dashboard/timeline",
    truth: "broken",
    endpoints: [E.vizTimeline],
  },

  // ── Pages with no backend calls (decorative / static) ─────────────
  {
    route: "/dashboard/blocks",
    truth: "decorative",
    endpoints: [],
  },
  {
    route: "/dashboard/command-post",
    truth: "decorative",
    endpoints: [],
  },
  {
    route: "/dashboard/workflows",
    truth: "decorative",
    endpoints: [],
  },
];

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

const _byRoute = new Map(ROUTE_TRUTH.map((r) => [r.route, r]));

/** Get truth for a specific dashboard route. */
export function getRouteTruth(route: string): RouteTruth | undefined {
  return _byRoute.get(route);
}

/** Get all routes matching a truth status. */
export function routesByTruth(status: TruthStatus): RouteTruth[] {
  return ROUTE_TRUTH.filter((r) => r.truth === status);
}

/** Summary counts for quick display. */
export function truthSummary(): Record<TruthStatus, number> {
  const counts: Record<TruthStatus, number> = {
    live: 0,
    partial: 0,
    decorative: 0,
    broken: 0,
  };
  for (const r of ROUTE_TRUTH) {
    counts[r.truth]++;
  }
  return counts;
}
